### ISSUE TITLE
ReactiveUserControl documentation is wrong

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#122]
The current documentation at https://reactiveui.net/api/reactiveui/reactiveusercontrol_1/ has:

```
<rxui:ReactiveUserControl
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
x:Class="views:AppView"
x:TypeArguments="vms:AppViewModel"
xmlns:rxui="http://reactiveui.net"
xmlns:views="clr-namespace:Love.Wpf.Views"
xmlns:vms="clr-namespace:Love.Wpf.ViewModels"
Height="450" Width="800">
```

This has multiple issues, including the Class being incorrect  etc.

It should be something more like this:
```
<reactiveUi:ReactiveUserControl x:Class="MyTool.Views.JobCommentsView"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
                                xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
      xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
      xmlns:reactiveUi="http://reactiveui.net"
      xmlns:viewModel="clr-namespace:MyTool.ViewModels.Jobs"
      d:DesignHeight="450"
      d:DesignWidth="800"
      x:TypeArguments="viewModel:JobViewModel"
      mc:Ignorable="d">
```

This was originally reported as a code bug https://github.com/reactiveui/ReactiveUI/issues/1684

**Comment by HeMinzhang** [comment]
I can't find [ReactiveUserControl<TViewModel>](https://reactiveui.net/api/reactiveui/reactiveusercontrol_1/) source code..

**Comment by HeMinzhang** [comment]
> <reactiveUi:ReactiveUserControl x:Class="MyTool.Views.JobCommentsView"
>       xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>       xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>       xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>       xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>       **mc:Ignorable="d"**
>       xmlns:reactiveUi="http://reactiveui.net"
>       xmlns:viewModel="clr-namespace:MyTool.ViewModels.Jobs"
>       d:DesignHeight="450"
>       d:DesignWidth="800"
>       x:TypeArguments="viewModel:JobViewModel"
>       mc:Ignorable="d">

I try add mc:Ignorable="d" code.and fix other error.

**Comment by glennawatson** [comment]
It would be under https://github.com/reactiveui/ReactiveUI/blob/master/src/ReactiveUI/Platforms/windows-common/ReactiveUserControl.cs
