### ISSUE TITLE
Get rid of all the chat logs in our documentation

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#139]
One thing that frustrated me a lot when first starting (and it's gotten better but not perfect) is chat logs in the documentation to talk about a feature. 

It is usually much harder to follow. We should target those chat logs and change them to proper documentation.

**Comment by RLittlesII** [comment]
@worldbeater I'll do my best to draft something about the current routing this weekend.  I have been digging through the API recently.

**Comment by worldbeater** [comment]
It seems to me there is no more pages with chat logs instead of proper documentation :)

**Comment by glennawatson** [comment]
Woot

**Comment by RLittlesII** [comment]
Then I say you do the honors and close out this issue @worldbeater

**Comment by ghuntley** [comment]
🥰
