### ISSUE TITLE
Expand how Command Parameters work and alternatives

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#150]
A user got very confused about our overloads for the CommandParameters and how they worked.

We probably need to expand the Command section to go more indepth, maybe have a example for Delete Item or something and how you can use CommandParameter or ViewModel property binding (and the ViewModel property binding is the more common). 

https://stackoverflow.com/questions/51870148/cant-bind-a-button-in-a-listview-to-viewmodel-using-reactiveui/51870526?noredirect=1#comment90693221_51870526

**Comment by srkeshav** [comment]
Can this be considered as done in #309 ? @glennawatson 
Small sample related to CommandParameter has been added in the documents based on this issue.

**Comment by glennawatson** [comment]
Seems reasonable.
