### ISSUE TITLE
Make a Work in Progress PR to remove ReactiveList 

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#159]
ReactiveList<T> is going away shortly.

We should have a document page pointing towards Roland Pheasants DynamicData page as a alternative https://github.com/RolandPheasant/DynamicData/wiki/Introduction-for-ReactiveUI-users and also https://github.com/RolandPheasant/DynamicData

Also we should remove ReactiveList, IReactiveCollection, IReactiveDeriveList etc all from our documentation. 

As alternatives we should be free to use DynamicData as example etc (it's likely it will become part of the ReactiveUI family anyway soon).

**Comment by glennawatson** [comment]
This PR should have [WIP] as it's prefix to avoid accidental checkin until RxList is put into Legacy/Obsolete mode.

**Comment by RLittlesII** [comment]
See also https://github.com/reactiveui/website/issues/156
