### ISSUE TITLE
Users need more context of what they are looking at

### ISSUE THREAD

**Issue by ghuntley** [reactiveui/website#16]
Here's a video of the problem:

[![](http://img.youtube.com/vi/EwqeKoPVDXQ/0.jpg)](http://www.youtube.com/watch?v=EwqeKoPVDXQ "")

# Background Information
* Website uses bootstrap v3, less and is generated by wyam.
* Instructions how to build the website is in the README.md

# Goals
* Report back with ideas, if the fix is simple then send in a PR right away
* If you want to changed everything up (this is okay) then please open a pull-request *when you start your work and incrementally ask for feedback*. **do not wait until work is finished before sending in the pull-request** (this will break my heart and your heart) - open one _right away_

**Comment by KallynGowdy** [comment]
IMO if I was someone who never knew about ReactiveUI or what it does, the homepage would be the most confusing. So, there are a couple of things that I would change with it:

1. The one-liner explanation only tells me that ReactiveUI is a "advanced, composable, and functional MVVM framework". As far as I'm aware, that's pretty much what every MVVM framework is (apart from the functional side). Maybe it would be better to focus on what ReactiveUI gives them? (e.g. "Gives you the power to build reactive, testable, and composable UI code using the familiar MVVM pattern")
2. Our list of features is below the community section. While I appreciate how much community is at the center of ReactiveUI, I'm assuming a lot of users don't really care at the moment they are trying to learn what ReactiveUI is and does for them.
3. We don't have a call to action. For what it's worth, I think this could simply be a prominent link to some getting started docs. The purpose is primarily to give them an avenue to learn more.

I could draft up these changes so we can discuss in a PR if anyone wants that too.

**Comment by ghuntley** [comment]
> IMO if I was someone who never knew about ReactiveUI or what it does, the homepage would be the most confusing. So, there are a couple of things that I would change with it:

Let's fix it.

> 1. The one-liner explanation only tells me that ReactiveUI is a "advanced, composable, and functional MVVM framework". As far as I'm aware, that's pretty much what every MVVM framework is (apart from the functional side). Maybe it would be better to focus on what ReactiveUI gives them? (e.g. "Gives you the power to build reactive, testable, and composable UI code using the familiar MVVM pattern")

This is a bigger part of the brand identity which is currently poorly defined. I'd like to see marketing basics fleshed out over at https://reactiveui.net/contribute/marketing/ fleshed out with the essentials:

* Product positioning
* Common problems developers that don't use Rx have but aren't a problem for developers who use Rx.
* Survey opinions of people using Rx; likewise for people who have tried; likewise for people with no exposure.
* Tone and Voice (started over at https://reactiveui.net/contribute/content-style-guide/voice-and-tone)
* Developer testamonitals (started here https://reactiveui.net/docs/overview/quotes-about-reactiveui) 

Current positioning is "There is a better way"

![image](https://user-images.githubusercontent.com/127353/29250098-ca69b7bc-807f-11e7-93d7-a27e661735be.png)

That might not be inspirational enough.

> 2. Our list of features is below the community section. While I appreciate how much community is at the center of ReactiveUI, I'm assuming a lot of users don't really care at the moment they are trying to learn what ReactiveUI is and does for them.

* Happy to refactor the community section with a call to action (see below). 
* Sponsors and backers must be above the fold or very close to it (we can't have features above it)

> 3. We don't have a call to action. For what it's worth, I think this could simply be a prominent link to some getting started docs. The purpose is primarily to give them an avenue to learn more.

100% agree. Okay so the best call to action (imho) for developers is "look; this is real. Download this application and run it through your debugger." 

> I could draft up these changes so we can discuss in a PR if anyone wants that too.

👍 open PR's early + happy to jump in a video call and pair with you on this stuff.

**Comment by ghuntley** [comment]
Let's keep this discussion on context and information design - moved homepage improvement discussion over at #22

**Comment by KallynGowdy** [comment]
Maybe [breadcrumbs ](https://en.wikipedia.org/wiki/Breadcrumb_(navigation))could help for mobile users? Not sure how we would implement them with Wyam though.
