### ISSUE TITLE
Broken menu on narrow screens

### ISSUE THREAD

**Issue by worldbeater** [reactiveui/website#163]
Looks good when I open a page:
![image](https://user-images.githubusercontent.com/6759207/44583007-34644480-a7ac-11e8-8dbf-3a1b620c9707.png)

Looks bad when I scroll it down:
![image](https://user-images.githubusercontent.com/6759207/44583020-46de7e00-a7ac-11e8-9e1a-02f88ebab9a3.png)

**Comment by ruliniyo** [comment]
which browser do you use?

**Comment by glennawatson** [comment]
I've tried on both Chrome/Firefox and can't reproduce on the mac versions. There have been some WYAM upgrades recently, can you confirm if still a issue @worldbeater

**Comment by ruliniyo** [comment]
Yes, now i understand, i tried with a screen of 900x1440 and problem persists. Right navigation menu fills the left menu. When you scroll down this happens 
![screenshot_2018-10-23 documentation](https://user-images.githubusercontent.com/11877941/47326954-80781c00-d66b-11e8-90bb-5d500712ac5d.png)
