### ISSUE TITLE
Documentation: Add Style Guide

### ISSUE THREAD

**Issue by RLittlesII** [reactiveui/website#166]
A blurb on using [CoreFx Style Guide](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md#c-coding-style) should be added
- https://reactiveui.net/contribute/software-style-guide/

This relates to https://github.com/reactiveui/ReactiveUI/issues/1733

**Comment by glennawatson** [comment]
I propose maybe {BEF9C138-DB4B-4993-83F7-6F4B74CAB3CD} as our Style Guid.
