### ISSUE TITLE
https://reactiveui.net/license results in 404

### ISSUE THREAD

**Issue by manne** [reactiveui/website#186]
On the website there are some links targetting <https://reactiveui.net/license>. The redirect in https://github.com/reactiveui/website/blob/2dd88e4964b401f1cebd0d239025739f87b651ea/input/_redirects#L9 references the `develop` branch, which does not exist. Should the redirect reference the `master` branch, or even a specific commit? I can submit a PR for this.

**Comment by RLittlesII** [comment]
@manne a link to the license on master is fine.
