### ISSUE TITLE
Integrate the Colt's cheat sheet content into our documentation

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#191]
We may want to incorporate somehow Colt's information from his cheat sheet guide: https://github.com/cabauman/Rx.Net-ReactiveUI-CheatSheet

**Comment by glennawatson** [comment]
@cabauman made the original documentation.

**Comment by cabauman** [comment]
This content now exists here: https://www.reactiveui.net/docs/handbook/when-activated/

We can close this one @glennawatson
