### ISSUE TITLE
Formatting issues with code samples in reactiveui.net

### ISSUE THREAD

**Issue by 1iveowl** [reactiveui/website#20]
Look at reactiveui.net  [Getting Started](https://reactiveui.net/docs/getting-started/).

Then look at the Github repo for the [same page](https://github.com/reactiveui/website/blob/master/input/docs/getting-started/index.md).

The Github version looks correct. The reactiveui.net page does not.

Notice how  `ObservableAsPropertyHelper<List<FlickrPhoto>> _SearchResults;` at Github becomes `ObservableAsPropertyHelper> _SearchResults;` at reactiveui.net

Looks like an issue with how the website inteprets the markup from github.

**Comment by ghuntley** [comment]
Your right - nice catch

![image](https://user-images.githubusercontent.com/127353/29245495-40a53b7e-801f-11e7-83af-473a91cbc27a.png)

Are you in a position to send in a PR? Instructions for building the website are in the README.md

Thanks

**Comment by RLittlesII** [comment]
Are we sure it isn't an issue with the way Wyam is converting the markdown to HTML?  The markdown in the file looks correct.  And it seems to be doing that with any angle bracketed generic typing on the page.

`public ReactiveCommand<string, List<FlickrPhoto>> ExecuteSearch { get; protected set; }` doesn't render correctly either.

**Comment by 1iveowl** [comment]
My hunch is that it is a converter issue too. 

I'm not sure why and how so I'm not sure how to create a PR.

**Comment by ghuntley** [comment]
Ta - tracking upstream at https://github.com/Wyamio/Wyam/issues/550

**Comment by daveaglick** [comment]
This is now resolved in Wyam 0.18.6

**Comment by 1iveowl** [comment]
Ok. Thanks for the update. 

The site still looks wrong but I guess the next convert will fix it then?

**Comment by daveaglick** [comment]
@1iveowl Yep, the fix is released upstream in the generator for the site but won't show up here until the next build and deploy.

**Comment by KallynGowdy** [comment]
FYI this looks resolved to me on the website.

**Comment by ghuntley** [comment]
Thank-you everyone for your help!
