### ISSUE TITLE
Create a upgrade guide for older RxUI versions

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#218]
Some advice to a user today yielded we may want to talk about the following in a upgrade guide from older versions:

1. `ReactiveCommand` needs to use the `ReactiveCommand<TParam, TResult>` form now.
2. Users should use the `PackageReference`, and limit their nuget reference for projects just to the top level they need, eg ReactiveUI.WPF https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference
3. Users need to worry about the new nuget packages available otherwise threading issues happen on WPF/Winforms and tricky bugs.
4. People get confused about DynamicData and how `SourceList` work, and think it's a one-on-one analogue. `SourceList` is usually hidden and you bind to a `ReadOnlyObservableCollection`. You only need `SourceList` if you are doing filter/transforming or multithreaded based operations. Otherwise `ObservableCollection` and `ObservableCollectionExtended` are both good alternatives for ReactiveList. SourceList/SourceCache more replaces the `IReactiveDerivedList` functionality and ObservableCollectionExtended adds Delayed notifications and range adding.

Anything else I missed?

**Comment by MarkusAmshove** [comment]
Today I've stumbled upon unit tests deadlocking (upgrading from 7.4 to 9.4).

As the super helpful people in Slack pointed out, it was because I had to subscribe to my commands in the unittests.

Before:

```
someCommand.Execute();
```

After:

```
someCommand.Execute().Subscribe();
```

**Comment by worldbeater** [comment]
UserError is replaced by https://reactiveui.net/docs/handbook/interactions/

**Comment by glennawatson** [comment]
* Dynamic Data -- more notes from previous section.
  * Use ObservableCollectionExtended if you aren't using DerivedList functionality and not using multiple threads.
   * Dynamic Data tries to expose using built in .net framework classes such as ReadOnlyObservableCollection<T>, SourceList<T>/SourceCache<TKey, TValue> are meant to be Bind() to those .NET types. Common mistake people make is trying to bind using the DynamicData instead of using Bind()
 * Our upgrade cadence is many releases, small number of changes, to make it easier to track bugs
    * Now using github release for release notes now instead of blog. Blog left for major changes
 * Maybe mention about how to use MsBuild.Sdk.Extras for multiple platform code, how we use that internally? https://github.com/onovotny/MSBuildSdkExtras (that one isn't strictlyly a upgrade thing though)
 * Colt has added some controls for helping with display data in apple/android lands that didn't exist previously in the build. We really need to get this stuff documented somehow.

**Comment by RLittlesII** [comment]
Seems this was addressed by #278

**Comment by worldbeater** [comment]
Marking as resolved. Thanks Glenn! :1st_place_medal:
