### ISSUE TITLE
docs/reactive-programming/schedulers.md mentions ReactiveList functionality

### ISSUE THREAD

**Issue by bezxyw** [reactiveui/website#256]
Hello, the url below is broken: 

The other thing that we use in some tests (e.g. if you're wanting to check whether the observable flips between some values during a few scenarios) is CreateCollection, e.g. [https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI.Tests/ReactiveCommandTest.cs#L35](https://github.com/reactiveui/ReactiveUI/blob/develop/src/ReactiveUI.Tests/ReactiveCommandTest.cs#L35)

**Comment by RLittlesII** [comment]
This is because there is no longer a develop branch.  Where did the link come from?  That would go a long way in helping us resolve this issue.

**Comment by bezxyw** [comment]
@RLittlesII 
Hello,
Yeah, sorry about that. Just clicked on 'report issue' directly on the webpage.

[https://reactiveui.net/docs/reactive-programming/schedulers](https://reactiveui.net/docs/reactive-programming/schedulers)

[https://github.com/reactiveui/website/blob/master/input/docs/reactive-programming/schedulers.md](https://github.com/reactiveui/website/blob/master/input/docs/reactive-programming/schedulers.md)

**Comment by glennawatson** [comment]
Todo: Remove the mention of the CreateCollection() on the following page https://reactiveui.net/docs/reactive-programming/schedulers and mention the DynamicData way of doing it with 

`fixture.Listen<int>("Test").ToObservableChangeSet(ImmediateScheduler.Instance).Bind(out var output).Subscribe();`

**Comment by RLittlesII** [comment]
@bezxyw Thanks for the links!  @glennawatson I will look into getting this clean up.

**Comment by worldbeater** [comment]
Worth referencing [reactivex.io](http://reactivex.io/documentation/scheduler.html) documentation instead of maintaining our own pages. I believe their website lives in [this repository]( https://github.com/ReactiveX/reactivex.github.io). Although Rx.NET sections are apparently empty on that website, maybe worth helping them with adding more content and links to ReactiveUI scheduling docs etc. 
![image](https://user-images.githubusercontent.com/6759207/51463528-7225c300-1d74-11e9-9b77-51d19d502a05.png)

**Comment by worldbeater** [comment]
The [reactive programming page](https://www.reactiveui.net/docs/reactive-programming/) is now rewritten, and the mention of `ReactiveList` is now removed from the website to the [`Obsolete`](https://www.reactiveui.net/docs/handbook/obsolete/collections/reactive-list) section. I believe this was done a while ago in https://github.com/reactiveui/website/pull/280, so closing the issue.
