### ISSUE TITLE
API Search Does Not Display Generic Type Params

### ISSUE THREAD

**Issue by KallynGowdy** [reactiveui/website#26]
![multiplereactivecommand](https://user-images.githubusercontent.com/5075285/29294437-578221aa-811d-11e7-8f80-fdac65071df1.PNG)
It looks like the API documentation does not display generic type parameters in the search results box. 
This can be annoying, especially when there are 4 results. 😆

Not exactly sure where to change the API output, so if someone wants to point me in the right direction I would appreciate it. Alternatively this might be an issue with Wyam, so we might have to report this upstream.

**Comment by ghuntley** [comment]
👍 Dis is going to have to be tackled upstream at Wyam. From our side the only special thing we really do is plumb the location into the `ApiDocs` pipeline. https://github.com/reactiveui/website/blob/master/config.wyam#L4

**Comment by KallynGowdy** [comment]
Reported: https://github.com/Wyamio/Wyam/issues/552

**Comment by daveaglick** [comment]
Got what I need to tackle this tomorrow, should be able to send a PR here with a small patch until the fix gets released in the template.

@ghuntley Feel free to assign any upstream issues here to me, that makes it easier for me to track issues in downstream consumers

**Comment by daveaglick** [comment]
This is now resolved upstream, will be released in a few days. I can submit a patch as a PR in the meantime if you want it (basically just drop a file into the `input` folder), but if it's not urgent may want to just wait for next release so you don't have to pull it back out.

**Comment by ghuntley** [comment]
Happy to wait until next release.
