### ISSUE TITLE
Fix validation URLs

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#266]
In my working version of Wyam with validation reports I had the following report, that ideally should be cleaned up.

[validation.txt](https://github.com/reactiveui/website/files/2777095/validation.txt)

**Comment by glennawatson** [comment]
[validation.txt](https://github.com/reactiveui/website/files/2777156/validation.txt)

Updated validation.

**Comment by ChrisPulman** [comment]
Website updated, no longer relevant.
