### ISSUE TITLE
OAPH or Opah

### ISSUE THREAD

**Issue by rvlieshout** [reactiveui/website#27]
[ObservableAsPropertyHelper](https://reactiveui.net/api/reactiveui/observableaspropertyhelper_1/) would suggest OAPH, however the section is named [Opah](https://reactiveui.net/docs/handbook/opah/).

**Comment by ghuntley** [comment]
I'm totally guilty of swapping the two around all the time. For the record the abbreviation should be the same spelling as the type. Thus OAPH. Can you please send in a PR?
