### ISSUE TITLE
Issue with docs/handbook/routing/index.md

### ISSUE THREAD

**Issue by dimacurotech** [reactiveui/website#294]
The page https://reactiveui.net/docs/handbook/routing/ mentions, but states nothing about:
- `public sealed class FirstViewModel`
  _Why_ is it sealed?
  _Why_ does it have a constructor where IScreen gets injected (in a context of Splash, which **does not support constructor injection**)?
- FirstView
  Should it be a view inheriting from a ReactiveContentView<FirstViewModel>?
- DataContext of FirstView:
  `() => new FirstView { DataContext = firstViewModel }`
  Should it be ` {ViewModel = firstViewModel }`?
- syncViewModel
  `Router.Navigate.Execute(syncViewModel).Subscribe();`
  Should it be *firstViewModel*?
- RoutedViewHost...
  Is it a view which inherits from ReactiveContentView<RouterViewModel>?
- XAML sample:
  `xmlns:rxui="http://reactiveui.net"` and `<rxui:RoutedViewHost`... WTF? WTF?! WTF!!!
  Should it be: `xmlns:v="clr-namespace:ReactiveUI.Example.Views"` and `<v:rxui:RoutedViewHost`?
- XAML sample:
  `Router="{Binding Router}"` - there is not such thing as Router, probably because of all the missing good documentation prior this point...

**Comment by glennawatson** [comment]
All good feedback, keep anything else you get confused about coming. We are actively working on this section as well.

**Comment by dimacurotech** [comment]
I'll update **this** comment when I am done "scanning" the article.

**Comment by glennawatson** [comment]
I think you made a fundamental mistake. This is the wpf documentation so all this example works fine.

**Comment by glennawatson** [comment]
Also splat has made a concious decision not to do constructor injection. The only realistic way to do it is via reflection (or expression trees which can't be compiled on iOS) so it can be a bottle neck on mobile. Hence why you tend to see the null check and Locator checks in the constructor. 

The only other way Todo it would be with a fody or a Roslyn based build task thing but again someone would have to write a adapter for splat. Happy to take a PR if you want to do that. 

In terms of the xaml be worth splitting the example based on platforms anyway

**Comment by dimacurotech** [comment]
Yeah, you must be right, I have been trying to use it for Xamarin.Forms, not for WPF.

It is clear why Splat has no constructor injection and it's totally fine to live with a service locator.

I will try to help with an article on implementing reactive-based routing within Xamarin.Forms when I find out myself how it should be implemented in a clear and simple manner.

**Comment by dimacurotech** [comment]
Sorry for late reply, I have been busy with another project. 
I think all the articles by Jamil Geor are great - I have checked them and they really have cleared out many points. Thank you for the link!

**Comment by ChrisPulman** [comment]
In it's current form the routing documentation demonstrates the basics of routing.
If anyone feels this should be re opened please do so with some feedback on what needs updating, many thanks.
