### ISSUE TITLE
WPF sample / tutorial glitch.

### ISSUE THREAD

**Issue by mark4asp** [reactiveui/website#301]
1) Is this actually working?
    
    Locator.CurrentMutable.RegisterViewsForViewModels();
    
While working my way through the WPF tutorial at  < docs/handbook/views/index.md >  I unable to get this (below) to type check. 
       
    namespace ReactiveDemo
    {
        using System.Reflection;
        using System.Windows;
        using Splat;

        public App()
        {
            Locator.CurrentMutable.RegisterViewsForViewModels(Assembly.GetCallingAssembly());
        }
    }

If it has been deprecated or otherwise vanished, someone should correct the tutorial.  Everything type checks apart from RegisterViewsForViewModels(). Is it an extension method?  If so, where is the code hiding?

**Comment by mark4asp** [comment]
Of course RegisterViewsForViewModels()  is an extension method. One needs to install  Splat.ReactiveUIExtensions and add the namespace : 
    using ReactiveUI;
Then it works.

I think someone should put that in the tutorial.

**Comment by glennawatson** [comment]
You don't need Splat.ReactiveUIExtensions, just need to put the `using ReactiveUI;` statement.

It's part of the main ReactiveUI nuget package.

Splat.ReactiveUIExtensions is some third party NuGet.

**Comment by glennawatson** [comment]
Also worth noting the source code can be found here https://github.com/reactiveui/ReactiveUI/tree/master/samples/getting-started
