### ISSUE TITLE
Issue with docs/handbook/interactions/index.md

### ISSUE THREAD

**Issue by albilaga** [reactiveui/website#303]
How Interactions should be integrated with `DisposeWith`? Because `Interactions` is usually used with control there are sometimes in many case when used with Command it will throw exception when view is already disposed and the command just finished (common usage is with TabBar in iOS, when we are change selected tab, it will raise DisposeWith in WhenActivated so it makes the Interactions unregistered) and make the app crash. Should it be all become static?

**Comment by tomasfil** [comment]
I suspect this is no longer actual. I can you still have issue with this, then please open it again, but please post code sample, which gives you issue. This is really broad.
