### ISSUE TITLE
Events API not getting Generated.

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#304]
We don't seem to be generating information about eventing api. probably should as part of wyam steps.

**Comment by RLittlesII** [comment]
You are explicitly talking about ReactiveUI.Events libraries?

**Comment by glennawatson** [comment]
Yeah, and it's derivates, ReactiveUI.Events.WPF etc.

**Comment by RLittlesII** [comment]
Looking at the generation.  We either need to check in the generated event files, or change the way we generate the api docs to look at the generated nugets.
https://github.com/reactiveui/website/blob/452f2b1f872d7405d03a7553f7d7f348a8a038b6/build.cake#L54
