### ISSUE TITLE
Issue with examples mentioned on website

### ISSUE THREAD

**Issue by slowik21861** [reactiveui/website#320]
Examples of Xamarin Forms have bugs (cannot compile with Visual Studio 2017 for Mac) and all other examples reference to old versions of framework. Documentation and all videos, blog posts and other media are obsolete.

**Comment by glennawatson** [comment]
Hey there. Can you provide specific examples. Going to close this specific bug since it's not something that can be actioned.

**Comment by slowik21861** [comment]
For example
https://github.com/reactiveui/ReactiveUI/tree/master/samples/xamarin-forms
Two examples in this folder use old versions of Nuget packages. After upgrade they cannot be compiled because of radical changes made in new version of library (9.x).
Initial example (https://reactiveui.net/docs/getting-started/) also uses older data types so I could not prepare this example by copy/paste from text to Visual Studio solution because with PowerShell command "Install-Package ReactiveUI.WPF" I just installed newest version of framework.

**Comment by glennawatson** [comment]
Cinephile is rxui 9.* Which is the xamarin example. The getting started works fine.

**Comment by glennawatson** [comment]
https://github.com/reactiveui/ReactiveUI/blob/8b0825e4882e57be5d1d0d008abd1c5eacd47d28/samples/xamarin-forms/Cinephile/Cinephile/Cinephile.csproj#L14

The master detail could be updated, will do that work soon.

**Comment by slowik21861** [comment]
Please, give me some time. Maybe I have made mistake copying code to VS. I prefer to prepare my own solutions instead of cloning repos. If I find any error, I will describe it in detail.
