### ISSUE TITLE
Issue with docs/handbook/when-activated/index.md

### ISSUE THREAD

**Issue by albilaga** [reactiveui/website#328]
Whenever you subscribe one object to an event exposed by another object, you introduce the potential for a memory leak. 

> This is especially true for XAML based platforms where objects/events referenced by a dependency property may not get garbage collected for you automatically.

according to discussion in here https://reactivex.slack.com/archives/C02AJB872/p1550076745066200 we don't need DisposeWith in Xamarin.Forms XAML right? Does it will make confusing as the docs state all XAML need to use `DisposeWith` when Bind?

**Comment by glennawatson** [comment]
Xaml based the documentation means platforms that use dependency properties. So wpf and uwp.

**Comment by glennawatson** [comment]
So yeah that part of the documentation could be improved.

**Comment by glennawatson** [comment]
XamForms use BindableProperty which sends INotifyPropertyChanged which we use on that platform. So they don't memory leak like the DependencyProperty since they we have to subscribe to events from a static manager.

**Comment by ChrisPulman** [comment]
The page does now state that dependency properties should be disposed in applications such as WPF
