### ISSUE TITLE
[Documentation][Bug] Documentation of overloads are indistinguishable

### ISSUE THREAD

**Issue by wischi-chr** [reactiveui/website#340]
**Describe the bug**
Open the documentation for a random method with multiple overloads for example
https://reactiveui.net/reactive-extensions/aggregate/

There is no way to distinguish most of  the elements.

**Steps To Reproduce**
1. Open https://reactiveui.net/reactive-extensions/aggregate/
2. Try to open the correct overload

**Expected behavior**
Show entire method definition

**Comment by RLittlesII** [comment]
Moved this issue because the files that need to change are part of this repository.

**Comment by olevett** [comment]
I started on this, but wanted to check before going down a massive rabbit hole that something like https://github.com/reactiveui/website/commit/1ca65282d17d7b9fe3a92ce8e4cb1c5f8bee2a55#diff-f32d04e2df06ba6bd75f4d8f6a542f5f is what's wanted

![image](https://user-images.githubusercontent.com/8627917/67207403-6eaa8f80-f40b-11e9-9304-fb7405146efc.png)

There's also a set of links that are a legacy of pulling this from the msft docs - presumably a separate issue would be most useful though.

**Comment by glennawatson** [comment]
Definitely a lot cleaner then what's there, so seems like a reasonable approach.

**Comment by cabauman** [comment]
This one was resolved by the merged PR mentioned above.
