### ISSUE TITLE
Issue with docs/handbook/view-models/index.md

### ISSUE THREAD

**Issue by Tridy** [reactiveui/website#351]
Following the text on the page and trying to build a simple ViewModel, in the code, the part that does the `.Select(x => x.Split(' ')[0])` will throw the NullReferenceException since by default the Name property is not initialized. So either it should be initialized to an empty string, for example or the _Select_ part should handle the the case when Name property is null:

![image](https://user-images.githubusercontent.com/7138873/64081598-bc582500-cd03-11e9-8110-7c95803f13c9.png)

or at least make a note in the text that the null case is not covered.

**Comment by glennawatson** [comment]
Thanks for this. I think just fixing it to handle nulls is the better option.

**Comment by glennawatson** [comment]
This has been fixed by #352
