### ISSUE TITLE
Issue with docs/handbook/routing/index.md

### ISSUE THREAD

**Issue by dallinbeutler** [reactiveui/website#353]
there is a 'view location' link that leads to a page that no longer exists
 (https://reactiveui.net/docs/handbook/views)

**Comment by RLittlesII** [comment]
Thanks for reporting this.  Seems the value changed to `docs/handbook/view-location/`

**Comment by ishitar** [comment]
Hi, how can I help?

**Comment by glennawatson** [comment]
Hi there. 

Any grammar or spelling improvements are most welcome to the website. 

Any existing issues fixes also most welcome. 

Any broken links fixed to their correct location are also welcome. 

Thanks
