### ISSUE TITLE
Issue with docs/getting-started/index.md

### ISSUE THREAD

**Issue by dprevato** [reactiveui/website#362]
I'm wondering what I'm doing wrong; I'm trying to follow the "getting started" example in your site, but I can't install the ReactiveUI.WPF package, because I receive an error NU1108: Cycle detected. this happen on a fresh solution, with a fresh WPF project (.Net Framework or .Net Core v3, I tried both with the same result).
Can you help me?

**Comment by glennawatson** [comment]
Mind putting the contents of what you are doing in a gist/repo for me to look at?

**Comment by MisinformedDNA** [comment]
@glennawatson Propose close for inactivity.
