### ISSUE TITLE
[Documentation] Custom DI docs are deprecated

### ISSUE THREAD

**Issue by rgomez90** [reactiveui/website#381]
**Is your feature request related to a problem? Please describe.**

The docs about custom dependency injection (https://reactiveui.net/docs/handbook/dependency-inversion/custom-dependency-inversion) are obsolete

• The interface `IMutableDependencyResolver` has a different API as in the docs.
•  `Locator.Current` has no public setter
• Autofac's `builder.Update(IContainer container)` is obsolete

**Describe the solution you'd like**

Updated documentation using https://github.com/reactiveui/splat/blob/master/src/Splat.Autofac/README.md

**Comment by RLittlesII** [comment]
The documentation may no longer be relevant because we have implemented them for you.  I would think keeping the explanation might have value in the event we don't have a package for a given DI container. 

The link you are proposing only shows you how to consume a package, not how to create it for yourself.

**Comment by rgomez90** [comment]
You're right. 

When I was looking for a way to use custom container with Splat, in the docs mentioned it was not clear (at least for me) there is already a package for Autofac.

This is the only reference to it in the page:

> Note: Some DI engines get locked away after they're being built and become immutable. For such services, the Use<MatchingService>DependencyResolver extension method (UseAutofacDependencyResolver in Autofac) must be called again on the locked container. See AutoFac docs.

Being 'docs' (the last word) a link to the `Splat.Autofac` package with your implementation.

So I would change a bit the text to make more clear there is already an implementation for Autofac.

**Comment by RLittlesII** [comment]
The docs where written before the packages were created.  I think it's worth listing the packages available on that page, and explain this is the technique if you don't find your DI container of choice.

**Comment by glennawatson** [comment]
Listing the packages available will add more maintenance overhead. Might be worth either doing wyam injection or similar. For first pass we can just link to the splat readme section.
