### ISSUE TITLE
Issue with docs/handbook/observable-as-property-helper/index.md

### ISSUE THREAD

**Issue by albilaga** [reactiveui/website#388]
In the sample, it looks like the 3rd param ( out param in `ToProperty(x1,x2,out var x3)` ) can be omitted but the fact is when we are not using out param we will receive null value when trying to access using `public string FirstName => firstName.Value;` and it will make binding error when using `this.OneWayBind()` with error saying `PropertyBinderImplementation: v.Label.Text Binding received an Exception! - System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.`

**Comment by glennawatson** [comment]
If you don't use the `out` value you must set your local field to use the return value.

**Comment by cabauman** [comment]
What Glenn said is correct, so I'll go ahead and close this issue. Feel free to reopen if you discover otherwise.
