### ISSUE TITLE
Issue with docs/handbook/data-binding/windows-presentation-foundation.md

### ISSUE THREAD

**Issue by imckl** [reactiveui/website#389]
It seems the code provided in View:
```
ViewModel = new TheViewModel();
```
just create a new instance of TheViewModel, and now we have two TheViewModel instances.
And any change in this TheViewModel will not reflect change to the origianl TheViewModel .

I've tested in 
ViewModel which inherited from MvvmCross MvxNavigationViewModel
View which inherited from MvvmCross MvxWindow, Implement IViewFor<ViewModel>

**Comment by imckl** [comment]
Assuming the View is Window, and when I put code in OnSourceInitialized
```
protected override void OnSourceInitialized(EventArgs e)
        {
            base.OnSourceInitialized(e);
            
            ViewModel = (MissionCreationViewModel) DataContext;
        }
```
It works as normal.
So it is a bug in the tutorial?

**Comment by imckl** [comment]
The correct implementation should be:
```c#
    public partial class MissionCreationView : IViewFor<MissionCreationViewModel>
    {
        public new MissionCreationViewModel ViewModel
        {
            get => DataContext as MissionCreationViewModel;
            set => DataContext = value;
        }

        object IViewFor.ViewModel
        {
            get => ViewModel;
            set => ViewModel = value as MissionCreationViewModel;
        }
    }
```

**Comment by glennawatson** [comment]
See comments in #390. Don't believe this is a valid issue.
