### ISSUE TITLE
GitHub logo is truncated

### ISSUE THREAD

**Issue by bitbonk** [reactiveui/website#394]
**Describe the bug**
The GitHub Logo in the top right appears truncated.

**Steps To Reproduce**
1. Open https://reactiveui.net in your browser (I tried Chrome, Vivaldi, Edge)
2. look at the GitHub logo in the top right corner and see that it is truncated

**Expected behavior**
It should not be truncated.

**Screenshots**
![image](https://user-images.githubusercontent.com/418030/72344021-8f177c80-36d0-11ea-8b39-17d6d45f692a.png)

**Environment**
- OS:       Windows 10
- Device:   Laptop
- Version:   1903
- Working Version: uknown

**Comment by glennawatson** [comment]
Most likely won't be instantly fixed but should be soon. Thanks for submitting the issue.
