### ISSUE TITLE
How to implement search busy indicator in 'Nuget Demo'?

### ISSUE THREAD

**Issue by CodingOctocat** [reactiveui/website#395]
I'm a Rx beginner, i want to implement search busy indicator in 'Nuget Demo' use Rx flavours, but I don't have a clue. how to do it?

**Comment by glennawatson** [comment]
Hey there, we ask that questions please be asked on [StackOverflow](https://stackoverflow.com/questions/tagged/reactiveui).

**Comment by glennawatson** [comment]
Alternatively please join Slack. At the moment due to spammers we've had to close Slack auto-invitations but if you ask on twitter to @anaisbetts she can help you join.

Thanks,
Glenn
