### ISSUE TITLE
Broken link. Issue with docs/handbook/events/index.md

### ISSUE THREAD

**Issue by artemious7** [reactiveui/website#398]
In the 2nd paragraph link to  Moustache template is broken. It points to https://github.com/reactiveui/ReactiveUI/blob/master/src/EventBuilder/DefaultTemplate.mustache which gives page not found

**Comment by glennawatson** [comment]
That whole page is out of date so this is a good reference to update it. 

Thanks for reporting it.

**Comment by worldbeater** [comment]
Seems to be fixed in https://github.com/reactiveui/website/pull/427 🎉
