### ISSUE TITLE
Issue with docs/guidelines/debugging/disable-just-my-code.md

### ISSUE THREAD

**Issue by ga15859** [reactiveui/website#400]
The link under "This is like Rx debugging pro-tip #1:" is obsolete and no longer pulls up the content you wanted to point people to.

**Comment by RLittlesII** [comment]
To be clear the link we are trying to fix is 404 from MSDN.  So we would need to track down where it changed to, or remove it completely.

http://blogs.msdn.com/b/davidklinems/archive/2005/07/18/440150.aspx
