### ISSUE TITLE
[BUG] Certificate expired

### ISSUE THREAD

**Issue by thargy** [reactiveui/website#430]
**Describe the bug**
Currently, users trying to navigate to reactiveui.net on Chrome will be stopped as the Certificate has expired this morning, and HSTS is enabled.  Other browsers (e.g. Edge) may let you access after clicking through a warning and opening advanced options.

**Steps To Reproduce**
Provide the steps to reproduce the behavior:
1. Go to 'reactiveui.net' (Which will navigate to 'https://reactiveui.net')

**Expected behavior**
You should be able to 

**Environment**
- OS:       Windows 10
- Device:   Chrome, etc.

**Additional context**
The Certificate:
Valid To: Monday‎, ‎June‎ ‎29‎, ‎2020 ‎9‎:‎00‎:‎27‎ ‎AM

**Comment by glennawatson** [comment]
Thanks,

It should be good now.
