### ISSUE TITLE
Issue with docs/handbook/routing/index.md

### ISSUE THREAD

**Issue by Ayajatra** [reactiveui/website#438]
Hello, I followed the documentation but the resulting behavior is different.

This is the expected behavior (the gif is from the documentation):
![routing](https://user-images.githubusercontent.com/43536431/87179026-47cd1a00-c308-11ea-9ff8-0c33dc84a85e.gif)

This is the actual behavior:
![routing acutal behavior](https://user-images.githubusercontent.com/43536431/87179973-d7bf9380-c309-11ea-9f5b-076af1588ef2.gif)

I can't go back to white screen.

**Comment by glennawatson** [comment]
What platform you running it on?

**Comment by Ayajatra** [comment]
I'm using WPF

**Comment by MisinformedDNA** [comment]
@glennawatson Propose close.
