### ISSUE TITLE
Revamp the Rx docs

### ISSUE THREAD

**Issue by cabauman** [reactiveui/website#441]
**Is your feature request related to a problem? Please describe.**

It's really awesome that we were able to persuade Microsoft to open source the Rx docs and get a copy on our website last year. But now, it's time to take it a step further and give it a facelift. Currently, most of the Github Markup links are broken, the folder hierarchy isn't user-friendly, and the lists that were formatted as tables on the Microsoft docs website are now giant blocks of text with no whitespace. After those items are taken care of I'd also like for us to gradually add some personal touches such as more code snippet examples, and short comments or explanations sprinkled around.

**Additional context**

Here's an example of a massive block of text with broken links: [https://www.reactiveui.net/reactive-extensions/observable/observable](https://www.reactiveui.net/reactive-extensions/observable/observable)

NameDescription![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[AsObserver<T>](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.asobserver%60%601(system.iobserver%7b%60%600%7d)(v=VS.103))Hides the identity of an observer.![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[Create<T>(Action<T>)](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.create%60%601(system.action%7b%60%600%7d)(v=VS.103))Creates an observer from the specified OnNext action.![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[Create<T>(Action<T>, Action)](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.create%60%601(system.action%7b%60%600%7d%2csystem.action)(v=VS.103))Creates an observer from the specified OnNext and OnCompleted actions.![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[Create<T>(Action<T>, Action<Exception>)](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.create%60%601(system.action%7b%60%600%7d%2csystem.action%7bsystem.exception%7d)(v=VS.103))Creates an observer from the specified OnNext and OnError actions.![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[Create<T>(Action<T>, Action<Exception>, Action)](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.create%60%601(system.action%7b%60%600%7d%2csystem.action%7bsystem.exception%7d%2csystem.action)(v=VS.103))Creates an observer from the specified OnNext, OnError, and OnCompleted actions.![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[Synchronize<T>(IObserver<T>)](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.synchronize%60%601(system.iobserver%7b%60%600%7d)(v=VS.103))![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[Synchronize<T>(IObserver<T>, Object)](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.synchronize%60%601(system.iobserver%7b%60%600%7d%2csystem.object)(v=VS.103))![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[ToNotifier<T>](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.tonotifier%60%601(system.iobserver%7b%60%600%7d)(v=VS.103))Creates a notification callback from an observer.![Public method](https://reactiveui.net/assets/img/Hh303103.pubmethod(en-us,VS.103).gif "Public method")![Static member](https://reactiveui.net/assets/img/Hh244319.static(en-us,VS.103).gif "Static member")[ToObserver<T>](https://msdn.microsoft.com/en-us/library/m:system.reactive.observer.toobserver%60%601(system.action%7bsystem.reactive.notification%7b%60%600%7d%7d)(v=VS.103))Creates an observer from a notification callback.Top

**EDIT (11/20/2020)**
I originally had a checklist of very manual tasks here, and actually got quite a bit done. But I soon realized the approach was not maintainable since, of course, we'd like to keep in sync with the Rx repo as much as possible. So I'd like to take a hybrid approach: creating a dll/xml-to-md generation tool for the API portion, and have a more manual section for things like getting started, how-to, snippets, etc.

**High Level TODO**

- [ ] Create a dll/xml-to-md generation tool.
- [ ] Port efforts by @IEvangelist (https://github.com/dotnet/docs/pull/21325)

**Comment by cabauman** [comment]
**Status Update**
I had originally planned on making a PR this past weekend with the basic fixes in place, but then I started going down a rabbit hole, experimenting with a custom xml-to-markdown parser. I expect to finish that up within the week, and then we can decide which route to proceed with. I'll probably make a separate branch for each to allow for easy comparison.

**Comment by quinmars** [comment]
I wonder if it wouldn't be better to generate the API documentation from Rx source code and extent the source code documentation were possible with the additional content from the Microsoft documentation. New operators would than be added automatically.

**Comment by glennawatson** [comment]
We don't control the source code for the Rx extensions this is a helper for our users.

**Comment by cabauman** [comment]
Because of what Glenn said, I'm making a tool to parse the System.Reactive dll and xml files myself.

**Comment by quinmars** [comment]
Ah, that sounds good. I'm pretty sure PRs, that improve the API documentation of Rx.NET, will be accepted. @glennawatson I understand that the website stuff is maintained in this repository. I was more concerned with manually synchronizing the dotnet/reactive source code documentation and the old MS documentation. When this effort flows back to dotnet/reactive, it only needs to be done once.

**Comment by glennawatson** [comment]
To be frank we've decided on a direction and given our justifications. So yeah happy for colt to continue.

**Comment by glennawatson** [comment]
Also to be frank this documentation update shouldn't consider flowing backwards. We are just interested in having a valid resource for rxui users that others may benefit from also. That way we can potentially make modifications where it makes more sense for rxui users

**Comment by glennawatson** [comment]
Seems to be confusion what this documentation is meant for. We aren't intending it go directly upstream to Rx but if it can benefit that team good and fine. It's meant to allow us to also deviate and provide rxui examples for operators not just pure Rx.

**Comment by glennawatson** [comment]
Accidentally deleted @quinmars post here is the contents

> Ah, that sounds good. I'm pretty sure PRs, that improve the API documentation of Rx.NET, will be accepted. @glennawatson I understand that the website stuff is maintained in this repository. I was more concerned with manually synchronizing the dotnet/reactive source code documentation and the old MS documentation. When this effort flows back to dotnet/reactive, it only needs to be done once.

**Comment by cabauman** [comment]
Hello @IEvangelist!
This is the issue I mentioned about our fork of the Rx docs and the hope to modernize/improve them. Any preferences on how you'd like to start porting your efforts? We'll start on a clean slate, so feel free to create a new branch (or I could create one; whatever you prefer).

**Comment by cabauman** [comment]
Starting work on this again.

**Comment by IEvangelist** [comment]
Hi @cabauman - I'm really sorry for not replying sooner. I'm honestly not sure how I missed this in the first place.

Feel free to tag me on reviews, and use any or all of the work that I had done here:
https://github.com/dotnet/docs/pull/21325. Happy to collaborate on this.

**Comment by cabauman** [comment]
@IEvangelist not a problem at all. Happy for the collaboration.
 
I'm thinking of doing the structure similar to [the old docs](https://docs.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh242985(v=vs.103)) where the sidebar contains both the generated API docs along with the authored content, which for the RXUI site would be [here](https://www.reactiveui.net/reactive-extensions/). Another option would be placing the authored content under [Documentation -> Reactive Programming](https://www.reactiveui.net/docs/reactive-programming/), separate from the generated API docs. Open to any suggestions.

**Comment by MisinformedDNA** [comment]
I noticed that all the links are broken [here](https://www.reactiveui.net/reactive-extensions/creating/creating). They all just need `../` prefixed to each URL. Is that what we want? Or is there supposed to be taken care of as part of the build?

**Comment by glennawatson** [comment]
Colt was doing a bunch of work on it then life happened with changing jobs etc

**Comment by ChrisPulman** [comment]
Website updated, section revised now using external documentation.

**Comment by cabauman** [comment]
@ChrisPulman can you link to where the revised section is?

**Comment by ChrisPulman** [comment]
> @ChrisPulman can you link to where the revised section is?

We are using a link to MS instead of replicating the docs in RxUI Docs - https://learn.microsoft.com/en-us/previous-versions/dotnet/reactive-extensions/hh242986(v=vs.103)
