### ISSUE TITLE
Issue with docs/handbook/data-binding/xamarin-forms.md

### ISSUE THREAD

**Issue by stephenhauck** [reactiveui/website#457]
It states "..but the Xamarin.Forms binding engine and XAML can also be used."

Can we get an example of how to do this properly using XAML ?

Thanks!

**Comment by glennawatson** [comment]
Expose properties, then set the BindingContext to be the ViewModel. It should follow the same as most xamarin form binding tutorials out there and fairly standard.

**Comment by stephenhauck** [comment]
I tried that ... 

I set the binding context like so 

![image](https://user-images.githubusercontent.com/12648793/91326199-0c8c8a80-e792-11ea-9b9a-2c7e22392c14.png)

Doesn't work ....

**Comment by stephenhauck** [comment]
forgot to include the view model 
![image](https://user-images.githubusercontent.com/12648793/91326461-5ffed880-e792-11ea-88c2-b3551ce9bc59.png)

**Comment by glennawatson** [comment]
Binding happens against properties not fields

**Comment by stephenhauck** [comment]
![image](https://user-images.githubusercontent.com/12648793/91366347-7f692600-e7d1-11ea-99f4-9c95bbea949e.png)
