### ISSUE TITLE
Issue with docs/handbook/data-binding/avalonia.md

### ISSUE THREAD

**Issue by SittenSpynne** [reactiveui/website#466]
A crucial part of setting up an Avalonia project is adding `UseReactiveUI()` to the configuration chain in Program.cs. This has been omitted from the documentation and I just spent an hour wondering why I couldn't do "Hello World" with Avalonia.

**Comment by glennawatson** [comment]
Yeah. I might talk to the avalonia guys about getting a section on their website for this since they manage the avalonia plugin.

**Comment by worldbeater** [comment]
We are mentioning the `UseReactiveUI` line here http://avaloniaui.net/docs/reactiveui/ and also here https://www.reactiveui.net/docs/getting-started/installation/avalonia I guess we should definitely reference one of those pages from `docs/handbook/data-binding/avalonia.md`. Will hopefully prepare a PR asap.

**Comment by glennawatson** [comment]
Probably worth us having a avalonia details page where we reference to the avalonia docs.

**Comment by SittenSpynne** [comment]
Yeah now that I've had more time to look over it (and got pointed to what I missed) I see it. I was sleepy and trying to get a "hello world" functional, and apparently missed both places that tell me to do it. Sigh.
