### ISSUE TITLE
Wrong WPF meaning?

### ISSUE THREAD

**Issue by snalesso** [reactiveui/website#47]
[Here](https://github.com/reactiveui/website/blob/master/input/docs/handbook/data-binding/windows-presentation-framework.md) WPF is presented as "Windows Presentation **Framework**", shouldn't it be "[Windows Presentation **Foundation**](https://en.wikipedia.org/wiki/Windows_Presentation_Foundation)"?

**Comment by ghuntley** [comment]
ugh yeah that's a mistake. Can you please send in a pull-request.

**Comment by ghuntley** [comment]
Fixed. Thank-you for reporting this.
