### ISSUE TITLE
Page cannot be found from link in docs/guidelines/debugging/disable-just-my-code.md

### ISSUE THREAD

**Issue by GarryPatchett** [reactiveui/website#481]
The link to the blog no longer yields a page: "Oops, 404 Error! That page can’t be found."

**Comment by worldbeater** [comment]
Should be fixed by https://github.com/reactiveui/website/pull/479 I guess. The fix is now [deployed](https://www.reactiveui.net/docs/guidelines/debugging/disable-just-my-code).
