### ISSUE TITLE
DesignTime 

### ISSUE THREAD

**Issue by JoschaHemlep** [reactiveui/website#49]
Hi,
it seems that the DesignTime example isn't working anymore (with Visual Studio 2017):
https://github.com/reactiveui/website/blob/master/input/docs/handbook/design-time/index.md
https://github.com/shiftkey/octohipster/blob/reactive-ui/OctoHipster/Views/ShellView.xaml#L6-L15

The first approach is working: ```<TextBlock x:Name="SomeField" 
                    Text="-this is design time-" />```

**Comment by ghuntley** [comment]
@JoschaHemlep which platform?

**Comment by JoschaHemlep** [comment]
The example is WPF. 
The constructor of the ShellView (UserControl) is not called during DesignTime -> no binding -> no DesignTimeData

**Comment by ghuntley** [comment]
I'm sorry to hear you are having problems with ReactiveUI! Can you please open a GitHub issue w/file -> new project that reproduces what you are experiencing please. ps. welcome to github!
