### ISSUE TITLE
Issue with docs/handbook/data-binding/xamarin-forms.md

### ISSUE THREAD

**Issue by justinasfour04** [reactiveui/website#493]
I think there should be some documentation that states that if a developer defined the base class as ReactiveContentPage in the XAML they do not have to define the base class in the C# code. Since the partial class gets generated with the XAML code there is no need to define it in the C# code. I spent almost 2 days scratching my head and looking at samples but that solved the issue. 

I'm on the latest VS 16.8.2 and DotNet 5.0.100.

If defined in one no need to define in the other

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/6599551/101199297-ad60d080-3632-11eb-9ca0-6b37aa354406.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/6599551/101199323-b487de80-3632-11eb-9b49-8230dc7d0a59.png)

**Comment by dpvreony** [comment]
thanks

this doesn't just apply to xamarin forms. this is a generic xaml issue. we probably need to do a xaml intro \ gotcha's page

other bits for example
* XAML and generic's

other resources
https://www.reactiveui.net/docs/getting-started/compelling-example
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/fundamentals/xaml?view=netdesktop-5.0
https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/code-behind-and-xaml-in-wpf?view=netframeworkdesktop-4.8
The latter link states
`The partial class must derive from the type that backs the root element.`
which as you touch on, isn't strictly true. explaining how a partial class only needs it to be defined in once place

**Comment by glennawatson** [comment]
Some platforms can't handle TypeArguments either and on those platforms you have to make your own derived class from ReactiveUserControl/ReactiveContentControl etc. UWP comes to mind.

So that content probably should be part of that help documentation.

**Comment by justinasfour04** [comment]
I'm glad I can help so that no one else has to scratch their head for more than needed

**Comment by glennawatson** [comment]
BTW might be worth doing a issue on that Microsoft post that david linked to where they aren't correct about the partial class.

**Comment by justinasfour04** [comment]
@glennawatson Created on the Microsoft page

**Comment by justinasfour04** [comment]
One thing I have to ask is why don't the Samples complain wen loaded up in VS?

**Comment by glennawatson** [comment]
I suspect maybe nullability? Eg those samples have nullability turned off. Also .net 5 is way more nullability aware.

**Comment by tomasfil** [comment]
Closing this, since this doesnt seem to be relevant anymore. In case open it and I will look into it.
