### ISSUE TITLE
Issue with docs/guidelines/platform/xamarin-mac.md

### ISSUE THREAD

**Issue by MonsieurTib** [reactiveui/website#500]
The documentation indicates to use our normal iOS concepts that we would usually use in OSX development, with a list of base class some of which are missing ( reactivetableview, reactivetableviewcontroller ) in reactiveui package.

**Comment by tomasfil** [comment]
Hello, do you have all the packages installed? https://www.reactiveui.net/docs/getting-started/installation/xamarin-ios

**Comment by MonsieurTib** [comment]
Hi,
My issue is 2 years old, I gave up

**Comment by tomasfil** [comment]
Hehe, yeah i know, but had to reply. I just started to help in Rx recently... Well if you wanna try, dont hesitate to contact me
