### ISSUE TITLE
Issue with docs/getting-started/compelling-example.md

### ISSUE THREAD

**Issue by belliste** [reactiveui/website#501]
Hi,
I replicated the example but I'm getting this error at line 116 of AppViewModel:
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=NuGet.Protocol
  StackTrace:
   at NuGet.Protocol.PackageSearchResourceV3.<SearchPage>d__7`1.MoveNext()

Framework 4.6.2
ReactiveUI.WPF.13.0.38
NuGet.Protocol.5.8.1

I tried framework  4.6.1 and .net core 3.1 too but the exception is still the same. I searched for breaking changes in NuGet.Protocol but I have found nothing.

Thanks
Stefano

**Comment by belliste** [comment]
Fixed adding: 
`ILogger logger = NullLogger.Instance; `
and passing it:
`var metadata = await resource.SearchAsync(term, filter, 0, 10, logger, token).ConfigureAwait(false);`

If it's correct please update the documentations
Thanks

**Comment by glennawatson** [comment]
You can provide a PR if you like
