### ISSUE TITLE
[BUG] The 'copy to clipboard' icon seems broken

### ISSUE THREAD

**Issue by bawkee** [reactiveui/website#502]
The copy to clipboard button that shows up in code samples appears as a broken image:

![2021-01-20_19-05-05](https://user-images.githubusercontent.com/38323343/105217030-a266ee80-5b53-11eb-9810-8ee013b28f99.png)

Example url: 
https://www.reactiveui.net/docs/handbook/commands/

I can see it's a SVG file (https://www.reactiveui.net/assets/img/clippy.svg) but it appears broken on all my devices, (Chrome/Edge/Safari).

**Comment by glennawatson** [comment]
Fixed by #510
