### ISSUE TITLE
Slack group invitation is expired

### ISSUE THREAD

**Issue by LBognanni** [reactiveui/website#503]
The slack group link appears to be expired. Has it been discontinued?

**Steps To Reproduce**
1. Go to https://www.reactiveui.net/slack
2. Try to join the slack group (I used google auth)
3. Slack says Invitation Expired
![image](https://user-images.githubusercontent.com/8505972/107121983-2a0b6780-688d-11eb-89a0-d4476737a473.png)

**Comment by glennawatson** [comment]
Thanks. 

Join my Slack workspace! https://join.slack.com/t/reactivex/shared_invite/zt-4aorc55t-ezSttwCF7Ta~BwyoSAHNxg

Try that link in the sort term and I'll update the website in the next 24 hours

**Comment by LBognanni** [comment]
The new link also says it's expired 😅

**Comment by glennawatson** [comment]
https://join.slack.com/t/reactivex/shared_invite/zt-madpq4m8-SnMuJHvTi3NG3sh3o9~aqw

**Comment by LBognanni** [comment]
Hey I tried the link from the homepage and it worked! 🎉 
I'll close this 😄
