### ISSUE TITLE
Support page not found

### ISSUE THREAD

**Issue by LBognanni** [reactiveui/website#504]
**Steps To Reproduce**
1. Go to the home page
2. Click on 'Support' in the main menu (https://www.reactiveui.net/support)
3. 404

**Comment by Arhell** [comment]
fixed

**Comment by glennawatson** [comment]
BTW tip with github 

You can do `fixes #1234` in your PR and it'll automatically close the issue for you.

See https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue

**Comment by Arhell** [comment]
https://github.com/reactiveui/website/commit/80034ebbf53ae9f24cbb2ea07edd6d7a5d6daa20#diff-1052b7a1bfaade5eeb2a4df135cf51a75b3edc04f352f9ca19111ca290228c10R21
