### ISSUE TITLE
Issue with docs/getting-started/compelling-example.md

### ISSUE THREAD

**Issue by deeks9000** [reactiveui/website#505]
```AppViewModel``` has a runtime error null exception at the line:
```var metadata = await resource.SearchAsync(term, filter, 0, 10, null, token).ConfigureAwait(false);```

This error is occurring with my own WPF .NET 5 'ReactiveDemo' app, following the Compelling Example tutorial instructions.
And, the GitHub Samples WPF getting-started 'ReactiveDemo'.

I am new to ReactiveUI and the fluent LINQ expression syntax so I apologise if I am being a bit dumb here!
I think it is complaining that the ```Nuget.Common.ILogger``` argument cannot be null?

So I made a simple class that fully implements ```Nuget.Common.ILogger```,
write out the logs to System.Diagnostics.Debug.WriteLine(...),
Then, within ```AppViewModel```, I create a class level variable _logger that is initialized in the constructor,
I then pass _logger as an argument to "resource.SearchAsync(...)"
```var metadata = await resource.SearchAsync(term, filter, 0, 10, _logger, token).ConfigureAwait(false);```

It now works!

**Comment by glennawatson** [comment]
I think the nuget API changed since the sample was made. Try NullLoger.Instance or something similar.

**Comment by deeks9000** [comment]
Thank you for the quick response!

It works also with your suggestion using NullLogger.Instance as the ILogger argument.

Might be worth adding this new info to the GitHub Samples WPF project, and the 'Compelling Example' tutorial?

Lots more for me to learn with ReactiveUI (and logging)! Awesome MVVM framework, thank you all.

**Comment by glennawatson** [comment]
Yeah I'll update the docs samples soon 

Thanks for the report.
