### ISSUE TITLE
Cannot build website locally

### ISSUE THREAD

**Issue by glennawatson** [reactiveui/website#53]
When I attempt to build the website locally I get the following error:

```
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Could not find any assemblies compatible with .NETFramework,Version=v4.5.
Error: Failed to install addin 'Cake.Git'.
```

I use the built in build.cmd on windows 10. I have installed 4.5 and also legacy through the windows feature website.

**Comment by dabutvin** [comment]
You can try deleting the tools folder and rerunning the build cmd. It should completely restore them to appropriate versions.

That may help..?

**Comment by glennawatson** [comment]
Now have the following instead 

```
Error: The assembly 'Cake.Wyam, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.17.0).
This assembly need to reference at least Cake.Core version 0.22.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

**Comment by dabutvin** [comment]
Yup. I get that too. If you run 

`set CAKE_SETTINGS_SKIPVERIFICATION=true` 

You should be up and running :)

**Comment by glennawatson** [comment]
Yeah, probably should be fixed regardless most likely, eg Geoff Huntley is suggesting the dev tool chain should be silky smooth, but thanks for getting me up and running.

**Comment by ghuntley** [comment]
Yup devchain needs to be silky smooth for everyone. Think this is happening because extensions we use are pinned at versions before Cake.Core 0.22.0 except for Cake.Wyam. Correct way to fix this to unpin and make everything work with Cake.Core 0.22.0.

**Comment by olevett** [comment]
@glennawatson is there any chance you would be able to test the PR I've put up? Hopefully it fixes the problems you've been having.
