### ISSUE TITLE
Issue with reactive-extensions/Buffer/Observable.Buffer.md

### ISSUE THREAD

**Issue by MGRussell** [reactiveui/website#618]
The documentation generation currently seems to be substantially borked. I am referring to the page at https://www.reactiveui.net/reactive-extensions/buffer/observable.buffer but this seems to be consistent throughout.

1) Lack of any formatting in the overload list. It's a single paragraph with no newlines.

2) Incorrect links. For instance the first link from that page on the Overload List section leads to: https://msdn.microsoft.com/en-us/library/m:system.reactive.linq.observable.buffer%60%602(system.iobservable%7b%60%600%7d%2csystem.func%7bsystem.iobservable%7b%60%601%7d%7d)(v=VS.103) which ends up being unresolved by MSDN and so leads to https://docs.microsoft.com/en-us/.

**Comment by RLittlesII** [comment]
I believe this is related to https://github.com/reactiveui/website/issues/441
