### ISSUE TITLE
RxApp.MainThreadScheduler seems off since 16.1.1

### ISSUE THREAD

**Issue by Thorocaine** [reactiveui/website#646]
**Describe the bug**

I don't know if this is a bug, or I am just doing something wrong.  
I updated to the latest Nuget (from **14.3.1** to **16.2.1** `ReactiveUI`, and `ReativeUI.XamForms`) and I started getting wrong thread exceptions in my UWP project.

I am using `RxApp.MainThreadScheduler`.
I set a breakpoint, and in the Immediate Window I do a quick `System.Threading.Thread.CurrentThread.ManagedThreadId`. I expect it to return `3`, but it was returning *random* numbers in the 20s.

I went back to the NuGets, and went down to **14.3.10**. I hit the breakpoint, my *test* returned 3, and the code ran.

I then tried **15.1.1**, that worked.
I then tried **16.1.1**, that did not work.

It might just be my solution, but `RxApp.MainThreadScheduler` doesn't seem to be working in the last two versions.

**Steps To Reproduce**

1. Update an existing Xamarin Forms app (UWP, in case it makes a difference) to ReactiveUI **16.1.1** or **16.2.1**.
2. Code relying on `RxApp.MainThreadScheduler` is running on the wrong thread.

**Environment**

- OS: **Windows 11**
- Device: **Alienware laptop**
- Version: **16.1.1, 16.2.1**
- Working Version: **15.1.1**

**Additional context**

I don't know if this is a bug, or it is just a quirk in my project.   
It is not critical for me, because 15.1.1 is working fine.  
Just FYI, and I am happy to try to answer questions if this looks like it might be a problem, and I am happy to close if it is just me.

**Comment by ChrisPulman** [comment]
Fixed with [#2999](https://github.com/reactiveui/ReactiveUI/pull/2999)
Please update to [16.3.10](https://github.com/reactiveui/ReactiveUI/releases/tag/16.3.10)

**Comment by Thorocaine** [comment]
I updated. Same problem.

**Comment by glennawatson** [comment]
Feel free to open new issues, old issues are hard to track. Thanks
