### ISSUE TITLE
contact page doesn't work

### ISSUE THREAD

**Issue by LanderVe** [reactiveui/website#66]
There is a link in the [contibute](https://reactiveui.net/contribute/) page that doesn't work

[https://reactiveui.net/contribute/Contact](https://reactiveui.net/contribute/Contact)

Can I contact somebody in a different way?

**Comment by olevett** [comment]
Thanks for spotting that :) I've updated the contribute page, if you need to get in contact with someone hello@reactiveui.net will get you a response, and there's also the slack organization (https://reactiveui.net/slack/)

**Comment by glennawatson** [comment]
Hi there, going to close this issue since I think @olevett took care of the issue mostly. We want most contact to also go through StackOverflow, Github or Slack rather than through a "contacts" page so I think this suits the purpose.
