### ISSUE TITLE
Issue with docs/handbook/when-activated/index.md

### ISSUE THREAD

**Issue by jeremy-morren** [reactiveui/website#682]
https://sharpfellows.com/post/Memory-Leaks-and-Dependency-Properties Link is broken.

**Comment by tomasfil** [comment]
Hello, where did you get the reference to this link? Was in somewhere on the docs page?

**Comment by MisinformedDNA** [comment]
>Whenever you subscribe one object to an event exposed by another object, you introduce the potential for a memory leak. This is especially true for XAML based platforms where [objects/events referenced by a dependency property may not get garbage collected for you automatically](https://sharpfellows.com/post/Memory-Leaks-and-Dependency-Properties).

**Comment by ChrisPulman** [comment]
Website updated.
