### ISSUE TITLE
Issue with docs/handbook/testing/index.md

### ISSUE THREAD

**Issue by rallets** [reactiveui/website#744]
Links to introtorx.com are broken

**Comment by tomasfil** [comment]
Which one exactly? This one works for me
![image](https://user-images.githubusercontent.com/34779382/179208804-9bc31b9d-584d-458f-992f-2df0bc2ad9ad.png)

**Comment by MisinformedDNA** [comment]
This one:

> If the view model needs multiple schedulers, you can use the ISchedulerProvider pattern described at [Testing Reactive Extensions](https://introtorx.com/Content/v1.0.10621.0/16_TestingRx.html) page

It's not broken, but it is very slow, sometimes timing out. Something is wrong with the SSL. HTTP calls are very speedy.

**Comment by ChrisPulman** [comment]
Website updated.
