### ISSUE TITLE
Issue with docs/handbook/interactions/index.md

### ISSUE THREAD

**Issue by mashbrno** [reactiveui/website#747]
I believe that `Observable` in the examples cannot be awaited directly, but has to be called with `.FirstAsync()`;

**Comment by glennawatson** [comment]
Effectively `await` in an async method will call this extension method https://github.com/dotnet/reactive/blob/9f2a8090cea4bf931d4ac3ad071f4df147f4df50/Rx.NET/Source/src/System.Reactive/Linq/Observable.Awaiter.cs#L20
