### ISSUE TITLE
Issue with docs/handbook/message-bus/index.md

### ISSUE THREAD

**Issue by kurtyoder** [reactiveui/website#752]
When using the example for the scenario, _a ViewModel of open documents containing a list of Document ViewModels - each Document containing a Close command_, I ran into an issue. When each of the documents was a tab page, it worked fine if I closed the *current* tab. If I closed a background tab, nothing would happen and I would be unable to close even the current tab.

When I switched out Switch() with Merge() it worked as expected.

> // to close, remove it from the list.
        OpenDocuments
            .ToObservableChangeSet()
            .AutoRefreshOnObservable(document => document.Close)
            .Select(_ => WhenAnyDocumentClosed())
            .Switch() //Replaced this with Merge()
            .Subscribe(x => OpenDocuments.Remove(x));

I am very new to reactiveui so I'm not sure why is this behavior happening. Is the example faulty or is there another explanation?

Could this possibly be related to https://github.com/reactiveui/website/issues/742#issue-1101542747?

**Comment by tomasfil** [comment]
Can you please create reproduction repository? Because I did not succeed to simulate your issue.

**Comment by ChrisPulman** [comment]
Unable to replicate
