### ISSUE TITLE
Issue with reactive-extensions/Observable/Observable.md

### ISSUE THREAD

**Issue by colejohnson66** [reactiveui/website#758]
The page is a mess. Is there supposed to be a table?

https://www.reactiveui.net/reactive-extensions/observable/observable

This affects any class documentation pages.

**Comment by colejohnson66** [comment]
The titles and navigation on the left seems to be forcing title case (capitalize the first letter, lowercase the rest). So [`IEnumerable` becomes `Ienumerable`](https://www.reactiveui.net/reactive-extensions/ienumerable.getenumerator/).

**Comment by ChrisPulman** [comment]
Website updated, section removed in favour of external documentation.
