### ISSUE TITLE
Issues with avatar images on main page.

### ISSUE THREAD

**Issue by TeddMcAdams** [reactiveui/website#76]
Hi all, found this project through [Up For Grabs](http://up-for-grabs.net).  Hope no one minds me poking around a bit and doing little stuff as I learn.

On to the issue I am reporting.  The avatars on the main page do not always load correctly.
Also in Microsoft's Edge browser, the sizing on the default generated 'user.svg' is broken.

![screenshot 2017-12-16 19 46 38](https://user-images.githubusercontent.com/15876990/34075670-15582574-e29b-11e7-8a4d-f89d2b4df32f.png)
![screenshot 2017-12-16 19 47 22](https://user-images.githubusercontent.com/15876990/34075667-02f62bce-e29b-11e7-9370-2bdce54a4537.png)

Working on pulling the files and building locally with this Wyam thing so I can try to see what's going on.
Not sure if it is an CSS issue or an issue with the plug-in.  One strange thing I've noticed, Edge centers the SVG somehow when viewing the file directly.

![screenshot 2017-12-16 19 58 41](https://user-images.githubusercontent.com/15876990/34075681-8e8b4be2-e29b-11e7-9c0d-03af17e334eb.png)

Generator: Adobe Illustrator 19.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)
http://opencollective.com/static/images/user.svg

**Comment by TeddMcAdams** [comment]
Replacing the image src does resolve the issue, so it appears to be something with the SVG.

![screenshot 2017-12-17 00 32 07](https://user-images.githubusercontent.com/15876990/34076920-2a5225b6-e2c2-11e7-862c-246c3d53fce5.png)

**Comment by TeddMcAdams** [comment]
I guess this is an issue with opencollective.com and it would be hard to set the dimensions in '_Sponsors.cshtml' since certain images have different dimensions.

**Comment by TeddMcAdams** [comment]
https://github.com/opencollective/frontend/issues/159

**Comment by olevett** [comment]
Thanks for spotting this, and raising a ticket in opencollective :)
