### ISSUE TITLE
[Bug]: Broken Links in Extensions

### ISSUE THREAD

**Issue by imundy7** [reactiveui/website#770]
### Describe the bug 🐞

Looking around "Extensions" in the ReactiveUI website, I noticed most of the links to Microsoft are broken and will take you to the main https://learn.microsoft.com site.

### Step to reproduce

1. Go to the ReactiveUI website (https://www.reactiveui.net)
2. Click 'Extensions'
3. Click 'Accept'
4. Click 'Notification<T>.Accept(IObservable<T>)'
6. Scroll down to 'Overload List'
7. Click 'Accept(IObservable)'

### Expected behavior

The links should take you to webpages that are specific to the link you clicked.

**Comment by ChrisPulman** [comment]
Website updated.
