### ISSUE TITLE
[Bug]: Broken links for "Using Rx"

### ISSUE THREAD

**Issue by franks1-svg** [reactiveui/website#776]
### Describe the bug 🐞

Many of the links for "Using Rx" on reactiveui.net do not redirect to the correct locations and instead display that the page was not found.

### Step to reproduce

1. Go to the ReactiveUI website (https://www.reactiveui.net/)
2. Click 'Extensions'
3. Scroll down and click 'Using'
4. Click 'Using Rx'
5. Click on any link that redirects to another ReactiveUI page
6. Page does not exist

### Expected behavior

Pages should redirect to correct locations.

For example, clicking 'Subjects' under the 'In This Section' block should redirect to https://www.reactiveui.net/reactive-extensions/subjects/subjects but instead redirects to https://www.reactiveui.net/reactive-extensions/using/Subjects/Subjects

**Comment by ChrisPulman** [comment]
Website updated.
