### ISSUE TITLE
[Bug]: Minor spelling error on front page

### ISSUE THREAD

**Issue by asda488** [reactiveui/website#808]
### Describe the bug 🐞

Minor spelling error on front page.

### Step to reproduce

1. Go to front page
2. Under "Scalable and Testable"
3. It says "Sytem.Reactive"

### Reproduction repository

https://github.com/reactiveui/ReactiveUI

### Expected behavior

Should be "System.Reactive"

### Operating system

Chrome/Windows

### Additional information ℹ️

Linked PR #809

**Comment by asda488** [comment]
Also, I should probably open a new issue, but are the main contributors aware that website/reactiveui/docs/index.md is broken due to the framework changes, as it has JS (other pages may be affected)?

**Comment by glennawatson** [comment]
Wasn't aware but would definitely would love an issue for it.
