### ISSUE TITLE
Boilerplate code page clarification needed

### ISSUE THREAD

**Issue by MaxwellDAssistek** [reactiveui/website#843]
### Describe the bug 🐞

On the boilerplate code handbook page there is a note saying "Note ReactiveUI.Fody currently doesn't support inline auto property initializers in generic types". This points to this issue: https://github.com/reactiveui/ReactiveUI/issues/2416. This issue is now closed saying that ReactiveUI.Fody is no longer maintained. So is this package no longer recommended? This is my first time using this project so I am not sure what to believe here.

### Step to reproduce

Go to https://www.reactiveui.net/docs/handbook/view-models/boilerplate-code#read-write-properties

### Expected behavior

If this is no longer an issue, the note should be removed.

**Comment by ChrisPulman** [comment]
ReactiveUI.Fody looks for a decorator and then replaces your code with the code as per the Fody template programmed at build time. The generated code is not visible to you unless you use a decompiler to view it. This method is restricted to templates and therefore it is harder to be flexible.
ReactiveUI.SourceGenerators can only add code to your code, the generated code is visible to you via the Analyser section of your project so you can be certain that no malicious code exists within the generated code. This code is generated real-time therefore you can use normal code at design time and the generated code where required will show in intellisence making your development experience better, more understandable and you know what code is being shipped.

There had been no changes to ReactiveUI.Fody for quite some time so it was taken out of the release system as the current version of ReactiveUI will work with ReactiveUI.Fody. You can use both ReactiveUI.Fody and ReactiveUI.SourceGenerators in the same project as the namespace of the Fody and Source Generators options are different.

If you are new to ReactiveUI and are not working on any existing code base that already has ReactiveUI.Fody then I would recommend ReactiveUI.SourceGenerators, there is more functionality available than the ReactiveUI.Fody option.

I hope that this answers your query and gives you some informative feedback for you to make a decision on which you decide to use.
Thank you.

I will close this now
