### ISSUE TITLE
Thanks page layout is not full width

### ISSUE THREAD

**Issue by olevett** [reactiveui/website#86]
![image](https://user-images.githubusercontent.com/8627917/34326288-d1f4150c-e8a0-11e7-93a5-67ed44696c93.png)
On the thanks page (https://reactiveui.net/docs/thanks/) the title and top level menu aren't full width, which looks a little strange.

**Comment by TeddMcAdams** [comment]
Curious what browser you are using? 

I am not able to reproduce this.

**Comment by TeddMcAdams** [comment]
Still new to Wyam so I'm not exactly sure where this is being generated from.

Issue is being caused by a @media query in the output theme.css file.

> @media only screen and (max-width: 1670px) and (min-width: 1250px) {

**Comment by TeddMcAdams** [comment]
https://wyam.io/api/wyam.docs/docskeys/7102d7b9

> NoContainer: false

This appears to be causing the issue.  I'm not sure if it was set to false for a specific reason.
Changing the value to true removes the CSS class that is causing this issue.

NoContainer: false
![screenshot 2017-12-28 22 55 21](https://user-images.githubusercontent.com/15876990/34429170-7177b500-ec22-11e7-9c08-5ed5123f2a06.png)

NoContainer: true
![screenshot 2017-12-28 22 54 37](https://user-images.githubusercontent.com/15876990/34429172-74c92360-ec22-11e7-9a18-e8fc5e0ea714.png)
