### ISSUE TITLE
Get Reactive UI Email layout quirk

### ISSUE THREAD

**Issue by olevett** [reactiveui/website#9]
Possibly in more places, but on a Surface Pro in Edge, the "Get The ReactiveUI Newsletter" is a bit out of alignment.

![image](https://user-images.githubusercontent.com/8627917/27659712-701c9b50-5c4c-11e7-9e8f-92e22a72f955.png)

I think this happens across pages, but certainly on the home page and the Concepts page.

**Comment by ghuntley** [comment]
Leaving this up-for-grabs; if you or anyone else wants to send in a PR that would be appreciated.

**Comment by ghuntley** [comment]
No longer relevant w/new website.
