### ISSUE TITLE
IObservable<T>.TakeWhile(...) does not accept a base Reactivecommand

### ISSUE THREAD

**Issue by NZSmartie** [reactiveui/website#95]
Following guide on cancelling ReactiveCommands at [docs/handbook/commands/canceling](https://github.com/reactiveui/website/blob/master/input/docs/handbook/commands/canceling.md#canceling-via-another-observable), The second example under **Canceling via Another Observable** shows that you may cancel an observable by taking advantage of the `.TakeUntil(...)` method and supplying another ReactiveCommand. 

This may be improved with an additional note saying that the `CancelCommand` Property needs to be explicitly defined with a `TParam` and `TResult`, since a bare ReactiveCommand does not implement an IObservable<T>, but a ReactiveCommand<TParam,TResult> does.

[src/ReactiveUI/ReactiveCommand.cs (v7.4.0)](https://github.com/reactiveui/ReactiveUI/blob/7.4.0/src/ReactiveUI/ReactiveCommand.cs#L633-L652)
```C#
/// <summary>
    /// A base class for generic reactive commands.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This class extends <see cref="ReactiveCommand"/> and adds generic type parameters for the parameter values passed
    /// into command execution, and the return values of command execution.
    /// </para>
    /// <para>
    /// Because the result type is known by this class, it can implement <see cref="IObservable{T}"/>. However, the implementation
    /// is defined as abstract, so subclasses must provide it.
    /// </para>
    /// </remarks>
    /// <typeparam name="TParam">
    /// The type of parameter values passed in during command execution.
    /// </typeparam>
    /// <typeparam name="TResult">
    /// The type of the values that are the result of command execution.
    /// </typeparam>
public abstract class ReactiveCommandBase<TParam, TResult> : ReactiveCommand, IObservable<TResult>
```

**Comment by worldbeater** [comment]
Closing this because that `ReactiveCommand` abstract class was completely removed by https://github.com/reactiveui/ReactiveUI/pull/1836 so there are no more confusing issues :)
